DavidVujic/python-polylith

bases/polylith/poetry_plugin/plugin.py, components/polylith/diff/__init__.py, components/polylith/diff/collect.py, components/polylith/diff/report.py, components/polylith/poetry/commands/__init__.py, components/polylith/poetry/commands/diff.py, components/polylith/workspace/create.py, components/polylith/workspace/parser.py, development/david.py, projects/poetry_polylith_plugin/pyproject.toml, pyproject.toml, workspace.toml
Adding a `poly diff` command.
The command will display the changes compared to the latest `git tag` (according to a configured pattern).
For CI builds, there is an option to add the `--short` flag. The output will be a comma separated list of project names only.
=> Feat: a poly diff command

components/polylith/interface/interfaces.py, components/polylith/test/tests.py, poetry.lock, pyproject.toml
Add support for python version 3.8
-
Built and imported in another Poetry project
=> Add support for python 3.8

components/polylith/diff/report.py, projects/poetry_polylith_plugin/pyproject.toml
The `poetry poly diff` command displayed unaligned columns, just like in #32 
This PR will adjust the columns better.
=> fix: align poly diff columns

README.md
Docs about the main use cases for Polylith for Python.
The motivation is the issues and solution in this Multiproject Pull Request: https://github.com/DavidVujic/poetry-multiproject-plugin/pull/27
Not applicable.
=> Add docs about main Use cases, and the issues with libraries & top namespaces

.circleci/config.yml, poetry.lock, test/components/polylith/bricks/test_base.py, test/conftest.py
fix: outdated poetry.lock file
fix: unit test namespace includes of bricks
dev: run pytest on CircleCI build
Some minor post-fixes after Pull Request #54 that solves issue #52.
=> fix: unit testing and linting

README.md
Added the CodeScene tool to analyze the health of the code base.
This PR adds a CodeScene badge to the README.md
https://codescene.com/
To keep the code base in a healthy state.
=> dev: add CodeScene analysis badge

components/polylith/diff/report.py, components/polylith/info/__init__.py, components/polylith/info/report.py, components/polylith/poetry/commands/info.py, projects/poetry_polylith_plugin/pyproject.toml
fix: adjust view for workspaces with many projects.
fix: poly info with different colors for bases and components.
Relates to Pull Request #103 
(the coloring of bricks bug was introduced in the pull request)
Local install and testing with python-polylith-example.
CI ✅
=> fix(poly diff): adjust view for many projects

components/polylith/poetry/commands/info.py
Fixing code smell reported by SonarCloud.
=> refactor(poly info): poetry info command with one exit branch

README.md
Add links to article and video.
Re-phrase the section about libraries, and direct users to the docs.
Share more solutions and ideas via articles and videos.
n/a
=> docs: add links to article and video - update libraries section

components/polylith/poetry/commands/check.py
`importlib.metadata` has `packages_distributions` which "Returns a mapping of top-level packages to their distributions." This is essentially what `poly check` needs on a silver platter!
Because Plugins don't run in the same environment, this leverages Poetry's `EnvManager` to get the proper environment's package to distribution mapping. Closely mirroring [packages_distributions](https://github.com/python/cpython/blob/97ce15c5f8743fb8b8967c6a05d6aec9fef9cbc7/Lib/importlib/metadata/__init__.py#L1043) from `importlib.metadata`, except keys/values are swapped to fit with existing code.
Using this, as long as the commands aren't being run in vacuum, fuzzy matching may not even be necessary~
I feel this more robustly solves https://github.com/DavidVujic/python-polylith/issues/107 
- Add and …
=> Get aliases from importlib.metadata

components/polylith/libs/report.py
Expect exact matches when running `poetry poly check`  with the `--strict` flag.
To avoid false-positives when checking installed libraries and imports.
Unit tests
CI ✅
=> fix(poly check, poly libs): strict check require exact match

poetry.lock, projects/poetry_polylith_plugin/poetry.lock
Update the sub-dependencies defined in poetry.lock.
To resolve issues highlighted by Dependabot (moderate and low).
unit tests ✅ 
CI ✅
=> fix(lock-file): update lock file to remove issues highlighted by Dependabot

poetry.lock, projects/poetry_polylith_plugin/poetry.lock, projects/poetry_polylith_plugin/pyproject.toml, pyproject.toml
Use latest version of `rich`.
CI ✅
=> Bump rich library

components/polylith/diff/collect.py, projects/poetry_polylith_plugin/pyproject.toml
Make sure the `poly diff` command is reporting on bricks.
Fixes #125 
Local install and test on the python-polylith-example repo
CI ✅
=> fix(poly diff): only report bricks

projects/poetry_polylith_plugin/mypy.ini, projects/poetry_polylith_plugin/poetry.toml
Remove accidentally added mypy and poetry configs in the project folder.
No need to have those files there.
CI ✅
=> fix: remove unused project-specific config files

projects/poetry_polylith_plugin/pyproject.toml
Bump version to v.1.12.1
Packaging a new release without the issues from third-party dependencies in the lock files.
CI ✅
=> fix: bump version to v1.12.1

projects/poetry_polylith_plugin/pyproject.toml, projects/polylith-cli/pyproject.toml
Bump CLI version to 0.3.0.
Bump Poetry plugin version to 1.14.2.
Changes in the `project` brick affects both projects. For the CLI, it is a new feature.
✅ CI
=> bump CLI and Poetry plugin versions

projects/hatch_polylith_bricks/pyproject.toml
Fix a typo in the entry point config for the hatch build hook.
=> fix: typo in Hatch build hook entry point

projects/hatch_polylith_bricks/poetry.lock, projects/hatch_polylith_bricks/pyproject.toml
Add missing `tomlkit` dependency to the Hatch Build Hook Plugin.
=> fix(hatch): add missing third-party dependency

components/polylith/project/templates.py, projects/hatch_polylith_bricks/pyproject.toml, projects/poetry_polylith_plugin/pyproject.toml, projects/polylith_cli/pyproject.toml
fix: typo in the Hatch project template (missing quotes)
fix: remove unnecessary poetry dev dependency section
Bump Hatch and CLI to v1.
Official support for Hatch!
✅ CI
✅ Local run of poly create project
=> feat: official support for Hatch

projects/hatch_polylith_bricks/README.md, projects/hatch_polylith_bricks/pyproject.toml
bump version to 1.1.1. 
Add docs about required hatch hook section.
A proper install instruction.
n/a
=> fix: add missing hatch hook docs

README.md
Add download stats for the CLI in the main README.
- Vanity metric for the maintainer.
- Validation about usage for users.
n/a
=> docs: add download stats for the CLI

README.md
Link to example repo using PDM.
To help users setup their projects with PDM.
n/a
=> docs: add link to PDM example repo

components/polylith/project/templates.py, projects/poetry_polylith_plugin/pyproject.toml, projects/polylith_cli/pyproject.toml, test/components/polylith/project/test_templates.py
fix(hatch): the project toml template with included build hook table.
Hatch need it to activate the Plugin.
✅ CI
✅ Added unit test assertions
=> fix(hatch): the project toml template

README.md, projects/polylith_cli/README.md, projects/polylith_cli/pyproject.toml
Add information about the support for Rye.
Add a quick start in the CLI docs for Rye.
To notify about the available support for the Rye tool.
n/a
=> docs(rye): add quick start and basic info

projects/hatch_polylith_bricks/pyproject.toml, projects/pdm_polylith_bricks/pyproject.toml, projects/poetry_polylith_plugin/pyproject.toml, projects/polylith_cli/pyproject.toml
Bump versions, feature:
Poetry plugin
CLI
Bump versions, fix:
hatch-polylith-bricks
pdm-polylith-bricks
Feature version bump: adding the possibility to configure the workspace in pyproject.toml, Pull request #166 
Fix version bump: used bricks are updated, no feature changes.
=> Bump versions supporting workspace config in project file

components/polylith/libs/report.py, projects/poetry_polylith_plugin/pyproject.toml, projects/polylith_cli/pyproject.toml
Fixed singular vs plural naming in the view returned by `poly libs`.
✅ CI
✅ Local testing of the libs command
=> fix(poly libs): naming typos

README.md, poetry.lock, projects/poetry_polylith_plugin/poetry.lock, projects/poetry_polylith_plugin/pyproject.toml
Update lock files for the Poetry plugin and for development.
To solve issues raised by Dependabot.
✅ CI
=> fix: update poetry lock files

projects/poetry_polylith_plugin/pyproject.toml, projects/polylith_cli/pyproject.toml, test/components/polylith/deps/test_deps_report.py
Adding a unit test asserting the merged fix #201 by @Peder2911 
bumping the CLI and Poetry plugin versions.
Asserting some of the functionality in the deps component.
=> fix: deps reporting

components/polylith/toml/core.py, projects/hatch_polylith_bricks/pyproject.toml, projects/pdm_polylith_bricks/pyproject.toml, projects/pdm_polylith_workspace/pyproject.toml, projects/poetry_polylith_plugin/pyproject.toml, projects/polylith_cli/pyproject.toml, test/components/polylith/toml/test_core.py
Include any third-party dependencies added as _optional_ when parsing the configurations during `poly check` and `poly libs`.
Details about optional dependencies: https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#dependencies-and-requirements
This will offer a solution to #206 where there are dependencies added from the runtime, and not as regular PyPI dependencies. The solution for a project would be to add the library there.
Example PEP 621 enabled configs (i.e. Hatch, PDM and Rye):
```
[project.optional-dependencies]
dev = ["awsglue-local-dev==1.0.0"]
```
Example for Poetry:
```
[tool.poetry.dependencies]
awsglue-local-dev = {optional = true}
```
✅ CI
✅ Unit tests
✅ Local run of the CLI commands
=> feat(poly check, poly libs): include optional third party deps

components/polylith/configuration/__init__.py, projects/pdm_polylith_bricks/pyproject.toml, projects/pdm_polylith_workspace/pyproject.toml, projects/poetry_polylith_plugin/pyproject.toml, projects/polylith_cli/pyproject.toml
fix: linting error in the configuration brick
Bump versions for:
- the PDM brick hook
- the PDM workspace hook
- the Poetry plugin
- the CLI
The Pull Request #212 is adding new features to the `poly diff` command. 🚀 
✅ CI
=> fix: linting + bump versions

components/polylith/distributions/collect.py, projects/poetry_polylith_plugin/pyproject.toml, projects/polylith_cli/pyproject.toml
Complements #220 
When running `poetry check` and `poetry libs`:
find the top namespace of a third-party library by extracting the packages distribution from the top-level virtual environment.
To not report on missing dependencies, when the top ns is only a part of the the added library name. Example importing "opentelemetry" and have added the library "opentelemetry-instrumentation-fastapi".
Note: this will introduce the risk of false-positives for libraries appending to the same top namespace.
=> fix(poly check, poly libs): always add packages-distributions, i.e. top ns fro library

components/polylith/commands/check.py, components/polylith/commands/libs.py, components/polylith/distributions/collect.py, components/polylith/distributions/core.py, components/polylith/poetry/commands/check.py, components/polylith/poetry/commands/libs.py, components/polylith/poetry/internals.py, projects/poetry_polylith_plugin/pyproject.toml, projects/polylith_cli/pyproject.toml
Get distributions data by using Poetry internals. This is used to resolve third-party dependencies in a proper way.
fixes #229 
✅ CI
✅ Local run of check and libs command
=> fix(poetry plugin - poly check, poly libs): get distributions

components/polylith/commands/diff.py, components/polylith/diff/collect.py, development/david.py, projects/poetry_polylith_plugin/pyproject.toml, projects/polylith_cli/pyproject.toml, test/components/polylith/diff/test_collect.py
Match changed files with regular expression, to solve issues with `poly diff` when using the TDD theme.
fixes #227 
✅ CI
✅ Unit tests
✅ Local run of the `poly diff` command
=> fix(poly diff): match changed files for chosen Polylith theme

bases/polylith/cli/core.py, bases/polylith/cli/options.py, components/polylith/commands/check.py, components/polylith/libs/report.py, components/polylith/poetry/commands/check.py, projects/poetry_polylith_plugin/pyproject.toml, projects/polylith_cli/pyproject.toml, test/components/polylith/libs/test_report.py
Compare library versions and report on differences.
This feature is added to the `poly check` command and **_will be a behavour change_** of the command, when using the `--strict` option.
Any version mismatch will return an exit code 1.
fixes #233 
✅ CI
✅ unit tests of the version diff calculation
✅ Local run of the `poly check` command
=> feat: calculate library version differences

README.md
Updating the docs, with relevant info for new users.
Feedback from a developer in a Python forum.
n/a
=> docs: update and rearrange the content in the README

poetry.lock, projects/poetry_polylith_plugin/poetry.lock
Bumpl lock files:
root project
poetry plugin project
To solve issues raised by Dependabot.
=> bump lock files

components/polylith/libs/stdlib.py, projects/poetry_polylith_plugin/pyproject.toml, projects/polylith_cli/pyproject.toml, test/components/polylith/libs/test_stdlib.py
Adding the changes between 3.12 and 3.13 (still in pre-release).
The list of builtins per version is needed to properly check imports.
✅ CI
✅ Unit test
✅ run poly commands with Python 3.13.0rc2
=> feat(Python 3.13): support Python 3.13 by adding the stdlib builtins list

bases/polylith/cli/core.py, components/polylith/commands/check.py, components/polylith/libs/__init__.py, components/polylith/libs/lock_files.py, components/polylith/toml/core.py, projects/poetry_polylith_plugin/pyproject.toml, projects/polylith_cli/pyproject.toml, test/components/polylith/libs/test_parse_lock_file.py, test/test_data/uv_workspaces
Adding support for the `uv workspaces` feature, and the shared lock-file in specific. This feature is for `uv` users and is added in the __Polylith CLI__.
The entire Polylith monorepo can use one single lock-file to manage all the third-party dependencies of individual projects.
This, by adding
```toml
[tool.uv.workspace]
members = ["projects/*"]
```
to the `pyproject.toml` file at the __root__.
This means that `uv` will pick up all the defined third-party dependencies from the individual projects and create one lock file at the root folder. The Polylith tool will analyze the contents of that lock-file to extract the library dependencies for an individual project. This is done when running `poly check` and `poly libs`.
As requested in #266 
This will very likely improve the developer …
=> feat(uv workspaces): add support for using a shared workspace lock-file

projects/polylith_cli/README.md, projects/polylith_cli/pyproject.toml
Removing incorrect instructions in the docs (README) about setting up a Workspace-specific. `pyproject.toml` file.
✅ CI
=> fix: Typo in the CLI README

components/polylith/commands/diff.py, components/polylith/diff/collect.py, development/david.py, projects/poetry_polylith_plugin/pyproject.toml, projects/polylith_cli/pyproject.toml, test/components/polylith/diff/test_collect.py
Add support for monorepos with the Polylith Workspace in a subfolder. Currently, the `poly diff` command fails, because of the mismatch between the underlying `git diff` and the workspace folder stucture.
The `git diff` command reports changed files from the git root folder. The changes in this Pull Request will collect the changed files, and create paths starting from the Polylith Workspace root.
fixes #288 
✅ CI
✅ Unit tests
✅ Local run of CLI `poly diff` command
✅ Local install of CLI and run in monorepo with the Polylith workspace in a subfolder of the repo
✅ Local install of the Poetry plugin and run in monorepo with the Polylith workspace in a subfolder of the repo
=> fix(poly diff): list of diff files with paths starting from the workspace-root

components/polylith/repo/repo.py, projects/hatch_polylith_bricks/pyproject.toml, projects/pdm_polylith_bricks/pyproject.toml, projects/pdm_polylith_workspace/pyproject.toml, projects/poetry_polylith_plugin/pyproject.toml, projects/polylith_cli/pyproject.toml
Fixes an issue with a Polylith Workspace in a sub-folder and when not using the `workspace.toml` for the Polylith-specific config.
The issue: failing to locate the workspace root.
fixes #295 
✅ CI
✅ Local install and run the `poly info` command in a monorepo that is set up according to the issue description.
=> fix(workspace root): check if path exist

components/polylith/hatch/hooks/bricks.py, projects/hatch_polylith_bricks/pyproject.toml
Adding support for editable installs in the Hatch project build hook.
A possible solution for the use case described in #302 
✅ CI
=> feat(hatch): add support for editable installs

components/polylith/libs/lock_files.py, projects/poetry_polylith_plugin/pyproject.toml, projects/polylith_cli/pyproject.toml, test/components/polylith/libs/test_parse_lock_file.py, test/test_data/uv_workspaces
Add support for optional dependencies in Polylith repos using uv workspaces.
fixes #318 
✅ CI
✅ unit test
=> feat(uv workspaces): add support for optional dependencies

components/polylith/libs/lock_files.py, projects/poetry_polylith_plugin/pyproject.toml, projects/polylith_cli/pyproject.toml, test/components/polylith/libs/test_parse_lock_file.py, test/test_data/uv_workspaces
Fixing an issue with the `poly check` command and when parsing the lock-file dependencies, where a library has sub-dependencies that themselves depend on the library. This caused a inifinite recursive loop when doing the name-and-version lookup.
Fixes #321 
✅ CI
✅ Unit Test
=> Recursive third party dependencies

README.md
Update the README with the FOSDEM 2025 Polylith recording, and links to articles.
✅ CI
=> docs: update with links to video and articles

components/polylith/parsing/core.py, projects/hatch_polylith_bricks/pyproject.toml, projects/pdm_polylith_bricks/pyproject.toml, projects/pdm_polylith_workspace/pyproject.toml, projects/polylith_cli/pyproject.toml
Fixing an issue with calculating paths with ignore/exclude patterns.
Continued work on #341  and #339 
✅ CI
✅ Local run of the `hatch build` command.
=> fix: Hatch hook exclude patterns
