- components/polylith/bricks/component.py
- components/polylith/info/report.py
- components/polylith/poetry/commands/create_workspace.py
- components/polylith/readme/readme.py
- components/polylith/test/tests.py
- components/polylith/workspace/create.py
- components/polylith/workspace/parser.py
- development/david.py
- workspace.toml
Add support for different workspace themes: tdd or loose. 
The `poetry poly create workspace` command now supports a `--theme` property.
(`tdd` is the default if no theme is set)
__tdd__ 
Create bricks according to the original Polylith implementation, such as:
`components/<package>/src/<namespace>/<package>` and `components/<package>/test/<namespace>/<package>`
__loose__
Create bricks in a (maybe) python style, such as:
`components/<namespace>/<package>` and `test/<namespace>/<package>`
> feat: workspace theme support + bug fixes

- components/polylith/bricks/base.py
- components/polylith/bricks/component.py
- components/polylith/diff/__init__.py
- components/polylith/diff/collect.py
- components/polylith/diff/report.py
- components/polylith/dirs/dirs.py
- components/polylith/info/__init__.py
- components/polylith/info/collect.py
- components/polylith/info/report.py
- components/polylith/poetry/commands/create_project.py
- components/polylith/project/__init__.py
- components/polylith/project/create.py
- components/polylith/project/get.py
- components/polylith/project/parser.py
- components/polylith/readme/readme.py
- development/david.py
Updated typing and sorted imports
> Update typing to support python 3.8

- components/polylith/diff/report.py
- components/polylith/poetry/commands/diff.py
- projects/poetry_polylith_plugin/pyproject.toml
The command did only react to changes within the actual project folder.
The changes in this PR will make the command print out a list of projects that are affected by changes in:
* components
* bases
* files in the actual project folder
> fix(bug): poly diff --short

- components/polylith/diff/report.py
- projects/poetry_polylith_plugin/pyproject.toml
Bug fix: merging with the pipe char won't work for Python 3.8.
> fix: unpack sets with python 3.8-syntax

- components/polylith/diff/collect.py
- components/polylith/diff/report.py
- components/polylith/info/__init__.py
- components/polylith/info/collect.py
- components/polylith/info/report.py
- components/polylith/poetry/commands/diff.py
- components/polylith/poetry/commands/info.py
fix: a bug when calculating diffs and rendering the brick name.
fix: don't render an empty bricks-changed table when there are no changes.
refactor: less brick iterations when rendering diffs and brick info.
> fix: poly info and poly diff

- .circleci/config.yml
Set the Python version explicitly in the CI config.
Run `mypy` to verify the Python syntax - to avoid introducing something not working in Python 3.8.
Fixes #30
> ci: add checks for Python syntax (to catch any usage of unsupported language features)

- components/polylith/interface/interfaces.py
- projects/poetry_polylith_plugin/pyproject.toml
Fixes an issue with the Python create-module template, that happens when passing in a `--name` that is a path (containing `/`).
Fixes #46 
CircleCI ✅ 
REPL-based tests
> fix: create-command with name as path

- components/polylith/poetry/commands/create_project.py
- components/polylith/project/create.py
- projects/poetry_polylith_plugin/README.md
- projects/poetry_polylith_plugin/pyproject.toml
The new description feature, released in v1.2.0 #50,  caused `create project` to fail.
This PR will fix that, and also enable the `--description` option into `pyproject.toml` files.
> fix(create-project): the new description feature caused create project to fail

- components/polylith/info/collect.py
- components/polylith/libs/report.py
- components/polylith/poetry/commands/libs.py
- components/polylith/project/__init__.py
- components/polylith/project/get.py
- projects/poetry_polylith_plugin/pyproject.toml
fix: normalize third-party library names when comparing what is imported and what is installed (i.e. treat `-` and `_` as same)
fix: use all third-party libraries, and don't filter out them by the "main" category.
NOTE: a trade-off is that the result might be a false-positive, if a dev-dependency would be imported into a brick.
fix: return to `stdout` (result code 1) when failing to extract libs from projects.
fix: use the project specific `poetry.lock` file when parsing third-party libraries.
Solves parts of  #58 - for the `poetry poly libs` command.
Fixes #57 
Manually tested
CI ✅
> fix: poly libs

- components/polylith/project/__init__.py
- components/polylith/project/get.py
When displaying the table with bricks and projects, the `poetry poly info` command should sort the projects alphabetically.
Also: removed unused function in the `projects` component.
Fixes #64 
1. Verified that projects are not sorted alphabetically, by running `poetry poly info` in the python-polylith-microservices-example workspace.
2. installed an updated, that is sorting projects
3. ran the same command again and confirmed that the sort order was: api_app, worker_1, worker_2.
> fix: poly info, sorted projects

- components/polylith/libs/imports.py
- components/polylith/project/create.py
- components/polylith/project/get.py
- projects/poetry_polylith_plugin/pyproject.toml
When analyzing source code, python files are opened in read mode. This PR aims to solve issues with unknown encodings, by setting `utf-8` explicit and ignore characters that cannot be parsed (`errors=ignore`).
Issue #73 
Local install
CircleCI ✅
> fix: poly libs and poly check - open files with encoding

- components/polylith/libs/report.py
- projects/poetry_polylith_plugin/pyproject.toml
- pyproject.toml
- test/components/polylith/libs/test_report.py
The current calculation of missing third-party libs is naive and will fail on libraries that differ in the name stated in `pyproject.toml` and the actual thing that is imported in python code.
This PR aims to calculate the diff by using "close matches".
Fixes #75 
Manual install
CircleCI ✅ 
Added unit tests for changed feature.
> fix(poly libs): calculate brick import diff by close matches

- components/polylith/project/get.py
Soft-get the `packages` section from a pyproject.toml file. This is because, since Poetry v1.4, a new project file doesn't contain that as default. For Polylith, this means when initializing a new repo and a new poetry project using `poetry init` according to the setup guide.
Local install and manual test.
CircleCI ✅
> fix(poly info): handle missing packages section.

- bases/polylith/poetry_plugin/plugin.py
- components/polylith/check/report.py
- components/polylith/diff/report.py
- components/polylith/imports/__init__.py
- components/polylith/imports/parser.py
- components/polylith/info/report.py
- components/polylith/libs/__init__.py
- components/polylith/libs/grouping.py
- components/polylith/libs/report.py
- components/polylith/poetry/commands/__init__.py
- components/polylith/poetry/commands/sync.py
- components/polylith/project/__init__.py
- components/polylith/project/get.py
- components/polylith/reporting/__init__.py
- components/polylith/reporting/theme.py
- components/polylith/sync/__init__.py
- components/polylith/sync/collect.py
- components/polylith/sync/report.py
- components/polylith/sync/update.py
- projects/poetry_polylith_plugin/pyproject.toml
- pyproject.toml
- test/components/polylith/sync/test_update.py
Keep projects in sync with the actual usage of components in source code.
Introducing a new command: `poetry poly sync`
This command will analyze and synchronize all projects in the workspace, including the development project.
Add the `--directory` flag to analyze one single project only.
For projects: will add missing brick dependencies, if imported by any of the already added ones.
For development: will add all missing dependencies.
solves #61
During development, it might be a risk of forgetting to add new components to the project specific `pyproject.toml` file actually needing it. Also, the development project should have all components added, to make it possible to run & experiment with bricks.
There's already the `poly info` and `poly check` command to catch any missing …
> Add poly sync

- components/polylith/sync/collect.py
- components/polylith/workspace/parser.py
- projects/poetry_polylith_plugin/pyproject.toml
Follow the brick imports of unknown bricks and synchronize with the already added ones, by using recursion.
Fixes #90 
Locally installed and added two new components to the python-polylith-example:
`hello` and `world`. The existing `message` component is importing `hello`, and `hello` is importing `world`.
Before: only `hello` was added. Now both `hello` and `world` are found and added.
> fix(poly sync): find sub imports of unknown bricks

- components/polylith/check/__init__.py
- components/polylith/check/collect.py
- components/polylith/check/report.py
- components/polylith/imports/parser.py
- components/polylith/poetry/commands/check.py
- components/polylith/poetry/commands/sync.py
- components/polylith/sync/collect.py
- components/polylith/sync/report.py
- projects/poetry_polylith_plugin/pyproject.toml
- feat: adding support for verbose output from the `poly sync` command, describing components and their imports.
-  fix: `poly check` command failing to report on missing bricks
- feat: adding support for verbose output from the `poly check` command, describing components and their imports.
- fix: cache modules that already have been parsed, when fetching imports
Fixes issue #101 
Discovered the `poly check` bug during development of the verbose feature, and decided to include a fix in this Pull Request.
Local install and test on the python-polylith-example repo.
CI build ✅
> feat: add support for verbose poly sync and poly check output

- components/polylith/info/report.py
- components/polylith/poetry/commands/info.py
- projects/poetry_polylith_plugin/pyproject.toml
fix: adjust the columns in the brick usages table when overflow: ellipsis instead of line breaks.
feat: add a `--short` option to the `poly info` command, that will display the brick usage view in a compressed mode.
To display brick usages in projects in a proper way, for workspaces with many projects.
Manual install and testing on the python-polylith-example repo, containing 5+ projects.
CI ✅
> feat(poly info): adjust view for workspaces with many projects

- components/polylith/check/report.py
- components/polylith/poetry/commands/check.py
- components/polylith/poetry/commands/sync.py
- projects/poetry_polylith_plugin/pyproject.toml
Run the `poly sync` and `poly check` without any output when passing in the `--quiet` flag.
The `poly check` command does already return an error code (1) to the stdout when there's missing dependencies or bricks.
Fixes #109 
- Local install, running all commands on the `python-polylith-example` repo. Running the `check` and `sync` commands with the `--quiet` flag.
- CircleCI tests
> fix(poly check and poly sync): respect the --quiet flag

- components/polylith/check/report.py
- components/polylith/libs/report.py
- components/polylith/poetry/commands/check.py
- components/polylith/poetry/commands/libs.py
The `--strict` option has a more narrow way of comparing third-party libraries and the actual imports. This is useful to rule out possible false positives.
Partially solves #107 
Manual install and run `check` and `libs` with, and without the `--strict` option. 
- Without: the `geopandas` import will be considered as "ok" because the `pandas` library is installed.
- With the `--strict` option: geopandas will be in the list of unknown imports.
> feat(poly check and libs): add --strict option

- components/polylith/alias/__init__.py
- components/polylith/alias/core.py
- components/polylith/poetry/commands/check.py
- components/polylith/poetry/commands/libs.py
- projects/poetry_polylith_plugin/pyproject.toml
- pyproject.toml
- test/components/polylith/alias/test_alias.py
Useful when an import differ from the library name, such as:
library name "opencv-python" and the actual import is "cv2". This will cause the `poly check` and `poly libs` to report missing dependencies.
The `--alias` option will help the commands with understanding the imports.
Example usage:
```bash
poetry poly check --alias opencv-python=cv2
```
With several aliases:
```bash
poetry poly check --alias opencv-python=cv2 --alias matplotlib=mpl_toolkit
```
Partially solves #107 
Local install and testing with the python-polylith-example repo.
> feat(poly check and libs): add --alias option

- components/polylith/poetry/commands/check.py
Fixes an issue with Python 3.8 and missing typings for `DefaultDict`.
To fix failing CI build for Python 3.8.
Local test runs.
CI ✅
> fix(typings): Python 3.8 defaultdict

- mypy.ini
Configure MyPy to find things that won't work in Python 3.8. 
To be notified early about the difference between the Python versions, such as missing `typing.Dict`.
> fix(mypy): catch Python 3.8-specific errors

- components/polylith/poetry/__init__.py
- components/polylith/poetry/commands/check.py
- components/polylith/poetry/commands/libs.py
- components/polylith/poetry/internals.py
- test/components/polylith/poetry/test_internals.py
Extract the `poetry` specific internals - the usage of `EnvManager` and the `locker` -  into a separate module.
This is a continuation of #115 
Refactoring and adding unit tests asserting the functionality is there also in future Poetry versions.
> refactor(poly check, poly libs): extract poetry internals

- components/polylith/diff/collect.py
- components/polylith/diff/report.py
- components/polylith/poetry/commands/diff.py
- projects/poetry_polylith_plugin/pyproject.toml
Add possibility to print changes only for bricks.
Adding the option `--bricks`.
As-is
```bash
poetry poly diff
```
As-is
```bash
poetry poly diff --short
```
New
```bash
poetry poly diff --bricks
```
New
```bash
poetry poly diff --bricks --short
```
This is useful when running tests for changed bricks only.
Fixes #116 
Example usage:
```bash
changes=$(poetry poly diff --bricks --short)
query=${changes//,/ or }
poetry run pytest -k <<< echo $query
poetry run pytest -m <<< echo $query
```
Local install and tested with the python-polylith-example repo.
CI ✅
> feat(poly diff): print changes for projects and/or bricks

- components/polylith/diff/collect.py
- components/polylith/poetry/commands/diff.py
- components/polylith/workspace/create.py
- components/polylith/workspace/parser.py
- development/david.py
- projects/poetry_polylith_plugin/pyproject.toml
- workspace.toml
Add possibility to have more than one git tag pattern, such as `stable` and `release`.
fixes #130 
TOML docs about Table structure: https://toml.io/en/v1.0.0#table
Clojure example: https://github.com/polyfy/polylith/blob/master/workspace.edn
Clojure docs: https://polylith.gitbook.io/poly/workflow/tagging
This will make it possible to calculate differences in a more fine-grained way.
Example:
the diff between a feature branch and the latest stable version (usually the main branch),
or the diff based on a release version.
usage: 
```shell
poetry poly diff
```
```shell
poetry poly diff --since release
```
Local install, tested on this repo + the python polylith example repo.
CI ✅
> feat(poly diff): multiple diff tag patterns

- components/polylith/commands/check.py
- components/polylith/distributions/__init__.py
- components/polylith/distributions/core.py
- projects/polylith-cli/pyproject.toml
- test/components/polylith/commands/test_check.py
- test/components/polylith/commands/test_info.py
- test/components/polylith/distributions/test_core.py
Gather sub dependencies when running `poly check` from the CLI. This, to allow imports from library sub dependencies in source code.
Example: fastAPI and using Pydantic models should be allowed. Same with Typer and the typing-extensions sub dependency.
Making the `poly check` command behave more correct when analyzing third-party dependencies.
✅ CI
✅ Local running manual tests
> fix(cli): gather sub-dependencies when runnint the poly check command

- components/polylith/commands/check.py
- components/polylith/commands/libs.py
- components/polylith/distributions/__init__.py
- components/polylith/distributions/collect.py
- components/polylith/poetry/commands/check.py
- components/polylith/poetry/commands/libs.py
- components/polylith/project/get.py
- projects/poetry_polylith_plugin/pyproject.toml
- test/components/polylith/commands/test_check.py
fix(cli): `poly libs` to collect sub-dependencies, as done in `poly check`.
Also, handling the collecting differently depending on if the source/origins is from a lock-file or not.
When gathering dependencies form a lock file: sub dependencies are already there.
To output more correct result for `poly libs` and the CLI.
Also, not extracting sub-dependencies when running in a `Poetry` context.
✅ CI
✅ run local CLI commands
✅ Local plugin install and run commands
> fix(poly check, poly libs): collect known aliases, with sub-dependencies when not from lock-file

- components/polylith/project/get.py
- test/components/polylith/project/test_project_get.py
Look for Polylith bricks in another TOML section, in addition to the Hatch build `force-include` section:
recursive lookup in the `tool.hatch.build` section and looking for `polylith.bricks`.
Preparing for building libraries in a Hatch context, to be used by a build hook.
This will also simplify the development of the Hatch build hook.
✅ CI
✅ Additional unit tests
> fix(hatch): lookup bricks in another TOML section

- components/polylith/project/get.py
- components/polylith/sync/update.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith-cli/pyproject.toml
- test/components/polylith/project/test_project_get.py
Add support for defining bricks in a separated TOML section, meant for a Build Hook to find and modify the Hatch build data.
`[tool.polylith.bricks]`
A step forward to support building libraries with a custom top-namepace when using Hatch.
✅ CI
✅ new/modified unit tests
> feat(cli): add Hatch library support

- components/polylith/project/templates.py
- components/polylith/repo/get.py
- projects/hatch_polylith_bricks/pyproject.toml
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
- test/components/polylith/repo/test_repo_get.py
Fix a bug with adding authors in the Hatch project template, happeing in `poly create project`.
Add missing bracket in hatch template.
✅ CI
✅ Local test running create project command.
> fix: PEP-621 template

- bases/polylith/cli/core.py
- bases/polylith/cli/options.py
- components/polylith/commands/deps.py
- components/polylith/deps/__init__.py
- components/polylith/deps/report.py
- components/polylith/poetry/commands/deps.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
Add a `--brick` option to the `poly deps` command.
It will visualize the dependencies for an individual brick: __used by__ and __uses__.
Fixes #172 
✅ CI
✅ Local install and running the deps command with options.
> feat(poly deps) introduce a zoomed-in view for individual bricks

- components/polylith/check/report.py
fix: the `poly check` command (using the `--verbose` option) crashing for Python versions lower han 3.12, because evaluating functions inline.
Solution: extract the string parsing and simplify the f-string usage.
fixes #193 
✅ CI
✅ Local testing with Python 3.8
> fix(poly check): f-string causing issues for Pythons less than 3.12

- poetry.lock
- projects/polylith_cli/poetry.lock
- projects/polylith_cli/pyproject.toml
- pyproject.toml
Remove the `all` extras from Typer, no longer neeed according to the [release notes](https://typer.tiangolo.com/release-notes/#0121).
Installing the CLI raises a warning in the terminal after installation/env creation.
✅ CI
> fix(cli): redundant Typer extras

- components/polylith/deps/report.py
I discovered a relatively harmless bug where `poly deps` will fail if a component imports another component, but is not itself imported anywhere. This leads to a KeyError in the visualisation code, which is probably not good. My fix is just to make the lookup return an empty set instead of raising an error.
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] I have read the [code of conduct](https://github.com/davidvujic/python-polylith/blob/master/CODE-OF-CONDUCT.md).
- [ x ] I have read the [contributing guide](https://github.com/davidvujic/python-polylith/blob/master/CONTRIBUTING.md).
- [ x ] I have updated the documentation accordingly (if applicable).
> Make `poly deps` work even though a component is not imported by anything.

- bases/polylith/pdm_project_hooks/core.py
- components/polylith/hatch/hooks/bricks.py
- components/polylith/pdm/hooks/bricks.py
- projects/hatch_polylith_bricks/pyproject.toml
- projects/pdm_polylith_bricks/pyproject.toml
- projects/pdm_polylith_workspace/pyproject.toml
Fixing an issue with the built `sdist` for hatch and pdm, indirectly also rye (using hatch).
Building wheels is not affected by this bug.
The issue is causing failed installs from an sdist, because the build hooks were triggered and trying to copy the relative bricks. 
This fix will exit the hook if there is no valid bricks to copy, i.e. from an sdist where all code is already put in place.
Making it possible to install a built library from an sdist.
✅ CI
✅ Locally running code in a REPL
> fix(hatch, rye and pdm hooks): building proper sdists

- components/polylith/configuration/__init__.py
- components/polylith/configuration/core.py
- components/polylith/diff/collect.py
- test/components/polylith/configuration/test_core.py
This change adds a new option to the `workspace.toml` configuration that allows you to change the behavior of the diff command when ordering tags.
The original behavior doesn't change, but this will allow you to use different sorting based on the `tool.polylith.tag.sorting` configuration, that is an array of options that are passed to the git command.
I wasn't able to find the right place to document this behavior, so any pointers to that would be great.
While integrating the polylith in a project, I noticed that there's a difference of behavior when using annotated tags, vs non annotated tags with the diff command.
When using annotated tags the `-committerdate` sorting option doesn't take into account the annotated tags, making the tags come back in an order that is not expected.
In the …
> Allow setting sorting options for git tags in diff command

- components/polylith/project/get.py
- components/polylith/toml/core.py
- projects/hatch_polylith_bricks/pyproject.toml
- projects/pdm_polylith_bricks/pyproject.toml
- projects/pdm_polylith_workspace/pyproject.toml
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
- test/components/polylith/project/test_project_get.py
Handle `KeyError` from tomlkit when fetching the project name, by adding extra information about the path to the project file with missing key.
To make it clearer where the problem happens.
Solves #215 
✅ CI
✅ added unitt tests
> Fix error handling when missing project name

- components/polylith/distributions/collect.py
- components/polylith/distributions/core.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
- test/components/polylith/distributions/test_core.py
Collect the top namespace for the package distributions.
Example:
Adding a third-party library that adds features into a sub-namespace, such as "google-cloud-storage".
Importing it in Python: `from google import cloud` or `from google.cloud import storage`.
The added feature will locate the top-namespace - i.e. `google` - based on the details of the package distribution data.
This should make the `poly check` and `poly libs` more correct, when analyzing and reporting on third-party dependencies, and less need for the `--alias` option.
Solving issues discussed in https://github.com/DavidVujic/python-polylith/discussions/209
✅ CI
✅ Unit test
✅ running the third-party libs lookup in the REPL
> feat(poly check, poly libs): include package distributions top namespace for known aliases

- components/polylith/project/get.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
Look for the project-specific `pyproject.toml` files at one sub-directory of the `projects` folder only.
Not traversing all sub-directories of each projects folder.
To avoid fetching any project files in a project-local `.venv` (even if that is not recommended to have there).
fixes #215 
This is a bug fix, and also a behaviour change and that is the reason for the minor version bumps in the Poetry plugin and in the CLI.
✅ CI
✅ Locally testing commands
> fix(projects): find project files at the sub directory of the "projects" folder

- components/polylith/distributions/collect.py
- components/polylith/distributions/core.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
- test/components/polylith/distributions/test_collect.py
- test/components/polylith/distributions/test_core.py
Parse the third-party library names that contains "extras", such as `uvicorn[standard]` and `python-jose[cryptography]`. The changes in this pull request will split the library name and extras into separate items in the result set, such as `uvicorn, standard, python-jose, cryptography`.
Also: properly parse distribution top-level namespaces where defined with `/`.
fixes #229
that was reported in https://github.com/DavidVujic/python-polylith/discussions/209#discussioncomment-10016618
✅ CI
✅ added unit tests
✅ local run of libs and check commands
> fix(poly check, poly libs): proper parse of third party lib names that contains extras

- components/polylith/alias/core.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
- test/components/polylith/alias/test_alias.py
Normalize the library name keys when performing the lookups from the distribution packages, third party library list and aliases (i.e. lower case strings before comparing).
fixes #237 
✅ CI
✅ unit test
✅ running commands locally (check, libs)
> fix(poly check, poly libs): discover libraries by comparing normalized names

- components/polylith/distributions/core.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
- test/components/polylith/distributions/test_core.py
Find top-level namespaces - the top folder name - by looking into the file paths list of a distribution.
This will add additional top namespaces to the list that is used when comparing imports in the modules with the installed libraries.
Some third-party libraries include sub-packages not as dependencies, but as adjacent packages.
One example is `pymongo` that includes the `bson` package.
See discussion covering this topic: https://github.com/DavidVujic/python-polylith/discussions/209#discussioncomment-10078102
✅ CI
✅ added unit test
✅ local run of the `poly check` and `poly libs` commands
> feat(poly check): parse any included top-level namespaces from the files list of a distribution

- components/polylith/distributions/core.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
- test/components/polylith/distributions/test_core.py
Handle missing distribution metadata errors, when doing distribution files list lookup.
To prevent errors for the `poly check` and `poly libs` commands for identified top-ns packages without metadata.
✅ CI
✅ added unit test
> fix(poly check, poly libs): handle missing metadata errors

- components/polylith/distributions/core.py
- components/polylith/poetry/internals.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
- test/components/polylith/distributions/test_core.py
Fixes an issue with querying the distribution metadata when using the `Poetry` plugin.
When running the poly commands within the Poetry plugin, the current environment is the one used by Poetry itself. This makes querying distributions using the `importlib.metadata` incorrect.
This Pull Request contains code that uses Poetry internals to fetch the distributions. The Poetry internals does a distribution discovery based on the current file path. This will produce a list of distributions that is located in the current path.
To be able to find adjacent packages like `bson`, added by libraries like `pymongo`.
Details in discussion: https://github.com/DavidVujic/python-polylith/discussions/209#discussioncomment-10078102
✅ CI
✅ unit tests
✅ Local install of the Poetry plugin, running the `poly …
> fix(poly check, poly libs): distribution files from package distribution object

- bases/polylith/cli/core.py
- components/polylith/commands/diff.py
- components/polylith/diff/report.py
- components/polylith/poetry/commands/diff.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
- test/components/polylith/commands/test_diff.py
Adding an option to the `poly diff` command - `--deps` - that can be used in combination with the `--bricks` option.
This will calculate the bricks that are dependent on the changed bricks.
This will add the possibility to run unit tests based on not only the changed bricks, but also the bricks that could be affected by the changes.
fixes #242 
✅ CI
✅ Local run of poly diff via the CLI
✅ Local install of the Poetry plugin, and running the poly diff command on the python-polylith-example repo
> feat(poly diff): include data for bricks dependent on changed bricks

- components/polylith/diff/report.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
The `--short` output should not be word wrapped, but should output a comma-separated string to be used programatically.
This fix will make sure the output isn't word wrapped or pretty-printed, by using the Rich feature `console.out` instead of `console.print`. Docs: https://rich.readthedocs.io/en/stable/console.html#low-level-output
fixes #245 
✅ CI
✅ Local testing the diff command with a long list of changed bricks.
> fix(poly diff): print --short output without word wrap

- README.md
- components/polylith/libs/lock_files.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/README.md
- projects/polylith_cli/pyproject.toml
- test/components/polylith/libs/test_parse_lock_file.py
- test/test_data/uv
Adding support for `uv`. 
`uv` is using the same build backend as `Rye` and the Polylith tool already works out of the box. The changes in this Pull Request is adding ability to read the uv-specific lock files called `uv.lock`.
To support as many Package & Dependency management tools as possible and reasonable. `uv` is a new (and experimental) tool, with interesting features and project goals.
✅ CI
✅ unit test
✅ adding a new example project: python-polylith-example-uv.
> feat: add support for uv

- components/polylith/repo/get.py
- projects/hatch_polylith_bricks/pyproject.toml
- projects/pdm_polylith_bricks/pyproject.toml
- projects/pdm_polylith_workspace/pyproject.toml
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
Missing `authors` section in a `pyproject.toml` causing an unhandled error, because setting default to a non-tomlkit data type.
Creating a `pyproject.toml` without authors should not crash the tool
✅ CI
> fix: missing authors in pyproject

- components/polylith/project/create.py
- components/polylith/project/templates.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
- test/components/polylith/project/test_templates.py
Allowing optional project `description` and `authors` when creating a project-specific `pyproject.toml` file.
To avoid forcing users to add these fields to the workspace `pyproject.toml`. Currently, the `poly create project` command will fail if the `authors` field is missing. I discovered that `uv` by default doesn't add the `authors` field when creating a new project.
fixes #259 
✅ CI
✅ Unit test
✅ Local run of Poetry plugin and CLI.
> fix(projects): allow optional authors and description

- components/polylith/commands/diff.py
- components/polylith/configuration/core.py
- components/polylith/diff/collect.py
- components/polylith/diff/report.py
- projects/pdm_polylith_bricks/pyproject.toml
- projects/pdm_polylith_workspace/pyproject.toml
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
- test/components/polylith/configuration/test_core.py
Allowing `poly diff` with a commit hash (by using the already existing `--since` option).
This also enables running the `poly diff --since` with a specific tag name, and not only the pre-defined pattern from the workspace configuration.
fixes #264 
✅ CI
✅ Unit test
✅ Local run of the `poly diff` command
> feat(poly diff): allow diff with commit hashes

- components/polylith/commands/check.py
- components/polylith/commands/libs.py
- components/polylith/distributions/collect.py
- components/polylith/libs/__init__.py
- components/polylith/libs/lock_files.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
- test/components/polylith/distributions/test_collect.py
Run `poly check` and `poly libs` in strict mode when the collected third-party depencencies is collected from a lock-file. 
This will have the same effect as when running the commands with the `--strict` option.
fixes #267 and the issue decribed in #266 
✅ CI
✅ Local run of `poly check` and `poly libs`
> feat(poly check, poly libs): use strict mode when dependencies origin from lock file

- components/polylith/libs/lock_files.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
- test/components/polylith/libs/test_parse_lock_file.py
Normalize the name that is specified in the project `pyproject.toml` files, before the member lookup in the `uv.lock` file.
This, because the uv tool list workspace member name without `_`, `.` and all in lower case.
Fixing the problem that the library dependencies won't be found when the project name contains any of the characters above.
✅ CI
✅ unit test
> fix: Normalize uv workspace member names before lookup

- components/polylith/commands/check.py
- components/polylith/libs/__init__.py
- components/polylith/libs/lock_files.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
- test/components/polylith/libs/test_parse_lock_file.py
Check if the root lock-file is workspace enabled, before trying to find member dependencies.
To fallback to the other ways of dependency and distribution data lookups if not found any workspace member data.
✅ CI
✅ Unit test
✅ Local run of commands
> fix(uv workspaces): check if the root lock-file is workspace enabled before picking member dependencies

- bases/polylith/cli/core.py
- projects/polylith_cli/pyproject.toml
Changing the data type from `str` to `bool` for the `--verbose` option.
The `str` annotation is a typo, the option is meant to be a boolean just like in other commands.
NOTE: this will be a __breaking__ change, for any users using the `poly sync --verbose` option today. My appologies if this is the case 🙏 . Hopefully this will be a minor thing to adjust (i.e. just use `--verbose` without any string value).
✅ CI
✅ Manual run of the `poly sync` command from the CLI endpoint.
> fix(cli): typo in the poly sync annotation for the --verbose option (BREAKING)

- bases/polylith/cli/create.py
- components/polylith/poetry/commands/create_project.py
- components/polylith/project/__init__.py
- components/polylith/project/get.py
- components/polylith/project/templates.py
- components/polylith/repo/repo.py
- components/polylith/toml/core.py
- projects/hatch_polylith_bricks/pyproject.toml
- projects/pdm_polylith_bricks/pyproject.toml
- projects/pdm_polylith_workspace/pyproject.toml
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
- test/components/polylith/project/test_project_get.py
- test/components/polylith/repo/test_repo.py
Adding support for the upcoming Poetry release, that will be PEP 621 compliant, and for those Poetry projects using the PEP 621 standard to define project metadata and dependencies.
To fully support Poetry, both as-is today and the future PEP 621 release.
✅ CI
✅ Unit tests
✅ Local install of the Poetry tool, running all commands.
✅ Local install of the CLI into a uv project, running all commands.
> feat(poetry plugin): add support for upcoming Poetry PEP 621 projects

- projects/hatch_polylith_bricks/pyproject.toml
Setting the minimum Python version to 3.8 (currently at >=3.9) for the Hatch Hook plugin.
To solve issues raised in #284.
✅ CI
> fix: allow Python 3.8 in Hatch build hook

- bases/polylith/cli/core.py
- components/polylith/check/report.py
- components/polylith/commands/check.py
- components/polylith/poetry/commands/check.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
Fixing the output from the `poly check --verbose` command. Currently, there are duplicated content for each project (that's a bug) and the imports are repeated for all projects sharing the same bricks. The output should be one collection of bricks and their imports. I have kept the separation of imported bricks and imported third-party libraries.
__Before__
(example from the Polylith repo itself, and the CLI project)
olylith repo and the CLI project):
__After__
fixes #291 
✅ CI
✅ Local run of CLI command
✅ Local install of the Poetry plugin
> fix(poly check): verbose output without duplication

- components/polylith/hatch/hooks/bricks.py
- projects/hatch_polylith_bricks/pyproject.toml
- test/components/polylith/hatch/test_hook.py
Fixes an issue with the Hatch build hook, as described in #307 and in a special use case described in #302
Solution:
filter the project-specific bricks when installed in _editable_ mode (i.e. `uv sync` or `hatch env create`) and when using the Hatch-specific `dev-mode-dirs`. Any paths matching the added bricks will be filtered. This will make it possible to create a virtual environment in dev-mode, without adding any bricks to the environment. This will solve the special use case described in #302.
The "editable" mode will be used only when in combination with the dev-mode-dirs, and this should solve the issue #307.
fixes #307 
fixes #302 
✅ CI
✅ unit test
✅ Local install of the Hatch hook and running `uv sync` with different configs (dev-mode, no dev-mode)
✅ Local install of the Hatch …
> fix: Hatchling dev-mode and editable installations

- README.md
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
Bumping the CLI and Poetry plugin versions. Adding notes in the README about Pixi support.
Changes made in #319 and #323 
n/a
> release updates for the new Pixi support

- components/polylith/commands/test.py
- components/polylith/test/core.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
Fixing a bug with how the affected bricks were collected.
✅ CI
✅ Local install and run of the Poetry plugin
✅ Local run of the CLI
> fix: poly test for test modules with same name

- bases/polylith/cli/core.py
This PR sets the `Typer` option `no_args_is_help=True`, so that in case of missing arguments the help text is displayed instead of an error.
Resolves #333.
Interactively by running `poly` without any arguments.
> feat(poly): display help page in case of missing arguments (#333)

- bases/polylith/cli/core.py
- projects/polylith_cli/pyproject.toml
This is only for the CLI: show the help page for sub-commands with missing arguments.
Adding on the work from #334 
✅ CI
✅ Local testing of CLI commands
> feat: display help page in case of missing arguments for sub-commands

- components/polylith/imports/parser.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
The `poly check` command performs AST parsing to find any missing bricks or third-party imports. A module that already have been parsed should be cached during the session. This is done since before, but with the default max size of `lru_cache`. For large Polylith workspaces, the cache need to be bigger.
See discussion #354 
✅ CI
✅ running the `poly check` command for a repo with 18+ projects, 350+ bricks and with large python files (20K LOC).
> fix: poly check performance for large repos

- components/polylith/imports/parser.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
Moving the caching of AST parsed modules one level up, to avoid re-running AST walking and inspecting for modules.
To improve the speed of the `poly check`command.
See discussion #354 
This Pull Request is a continuation of the work in #355 
✅ CI
✅ running the command on a polylith workspace with many projects and many components.
> fix: poly check performance improvement

- components/polylith/parsing/rewrite.py
- projects/hatch_polylith_bricks/pyproject.toml
- projects/pdm_polylith_bricks/pyproject.toml
- projects/pdm_polylith_workspace/pyproject.toml
- projects/polylith_cli/pyproject.toml
Fixing an issue with rewriting the top namespace for bricks, when the brick is imported as: 
```python
import the_namespace
```
The code using this import will fail if the import is rewritten without an alias. This PR will fix this.
Originally fixed in the Poetry Multiproject plugin (a separate repo): https://github.com/DavidVujic/poetry-multiproject-plugin/pull/76
✅ CI
> fix(rewrite): add module name to alias for plain imports and when not already using alias

- components/polylith/distributions/__init__.py
- components/polylith/distributions/caching.py
- components/polylith/distributions/core.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
- test/components/polylith/distributions/test_core.py
Improving the performance of the `poly check` command, when doing _dists_ lookups.
This should make the command faster.
Distribution lookups (via the `importlib` builtin) are expensive from a performance perspective. The metadata and `files` fetching is performing I/O actions. In this PR: caching any already performed lookups for a specific distribution (by the dist name).
✅ CI
✅ Local run on a large Polylith monorepo
> fix(poly check): dependency/dists lookup lookup performance improvements

- bases/polylith/cli/create.py
- components/polylith/commands/sync.py
- components/polylith/info/__init__.py
- components/polylith/info/collect.py
- components/polylith/poetry/commands/create_project.py
- components/polylith/project/__init__.py
- components/polylith/project/interactive.py
- components/polylith/sync/__init__.py
- components/polylith/sync/collect.py
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
Adding the possibility to interactively add base(s) and components to a newly created project.
`poly create project` will create the project data as before. If there are any unused bases in the Polylith workspace, the user will be asked to add a base to the project. Any other needed bricks (basically a `sync` operation) will be added to the newly created project.
This is an idea coming from Discussion #352 ⭐ 
✅ CI
✅ Manually running the `poly create project` command
> feat(poly create project): interactively suggest base and components to add

- README.md
Removing the download badges from pypistats (hopefully temporary).
Replacing with static stats, originating from Clickhouse and pepy.tech.
The Pypistats service seems to be unmaintained, and has been offline for more than one week. In case the service will be online again, the changes of this Pull Request will be reverted.
More content in this pypistats issue:
https://github.com/crflynn/pypistats.org/issues/82
> Remove pypistats until the api is online again

- bases/polylith/cli/core.py
- bases/polylith/cli/options.py
- components/polylith/commands/deps.py
- components/polylith/commands/info.py
- components/polylith/commands/libs.py
- components/polylith/configuration/__init__.py
- components/polylith/configuration/core.py
- components/polylith/deps/report.py
- components/polylith/info/__init__.py
- components/polylith/info/report.py
- components/polylith/libs/report.py
- components/polylith/output/__init__.py
- components/polylith/output/core.py
- components/polylith/poetry/commands/check.py
- components/polylith/poetry/commands/command_options.py
- components/polylith/poetry/commands/deps.py
- components/polylith/poetry/commands/diff.py
- components/polylith/poetry/commands/info.py
- components/polylith/poetry/commands/libs.py
- components/polylith/poetry/commands/test.py
- components/polylith/repo/__init__.py
- components/polylith/repo/repo.py
- components/polylith/test/report.py
- projects/pdm_polylith_bricks/pyproject.toml
- projects/pdm_polylith_workspace/pyproject.toml
- projects/poetry_polylith_plugin/pyproject.toml
- projects/polylith_cli/pyproject.toml
- pyproject.toml
- test/components/polylith/output/test_core.py
Adding a `--save` option to the `poly deps`, `poly info` and `poly libs` commands. In addition to printing the output (as before) a file will be saved with the contents of the output.
The location is by default in `development/poly/<command name>.txt`, but is configurable.
Saving the result from the `deps`, `info` and `libs` commands is useful during Pull Requests, when reviewing code. Besides the code diff, the changes in saved commands will give the reviewer an overview of the changes such as coupling and dependency changes.
The idea comes from the discussion #365
✅ CI
✅ Local run of commands with the new `--save` option
✅ unit test
> feat(poly deps, info, libs): save contents to file command option
